name: Deploy Hetong Flask to Vercel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取完整 Git 历史（修复 git log 错误）
      - name: Checkout Hetong Repo
        uses: actions/checkout@v4
        with:
          repository: peter-zx/hetong_20251027
          ref: main
          token: ${{ secrets.PAT_TOKEN }}
          path: hetong
          fetch-depth: 0  # ← 关键修复：拉取全 Git 历史，初始化 .git

      # 2. 验证目录（可选，调试用）
      - name: Verify Git Repository
        run: |
          cd hetong
          pwd
          ls -la
          git status  # ← 测试 Git 是否正常
          git log -1 --pretty=format:%B  # ← 测试 git log

      # 3. 安装 Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 4. 安装依赖
      - name: Install Dependencies
        run: |
          cd hetong
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. 部署到 Vercel（现在 Git 可用）
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          working-directory: ./hetong
          vercel-args: '--prod'
